<?php 
	session_start();
  	if(!isset($_SESSION['id'])){
    	header("Location: home-search.php");
  	}
  	
  	$userid = $_SESSION['id'];	
	$oldPassword = $_POST["oldPassword"];
  	$newPassword = $_POST["newPassword"];
  	$confirmPassword = $_POST["confirmPassword"];

  	// check if newPassword matches confirmPassword
  	if($newPassword !== $confirmPassword) {
  		header("Location: change-password.php?fail=true");
  	}
  	// check if oldPassword matches the password of the logged in user
  	else {
  		include("database-connector.php");

	  	$sql = $conn->prepare("SELECT * FROM user WHERE usc_id = ?;");
	  	$sql->bind_param('s', $userid);
	  	$sql->execute();
	  	$ans = $sql->get_result();
	  	$row = $ans->fetch_assoc();
	    $passHash = $row['password'];

	    // verify if passHash, the hash generated by password_hash(), matches the old password
	    if(password_verify($oldPassword, $passHash)) {
	    	$newPassHash = password_hash($newPassword, PASSWORD_BCRYPT);  // password hash that is generated
	    	$sql = $conn->prepare("UPDATE user SET password = ? WHERE usc_id = ?;");
	        $sql->bind_param('ss', $newPassHash, $userid);
	        $sql->execute();  
	      	header("Location: user.php");
	    }
	    else {
	      	header("Location: change-password.php?fail=true");
	    }
  	}
?>