<?php
	session_start();
  session_unset();
  include("database-connector.php");
  $username = $_POST['loginID'];
  $password = $_POST['loginPassword'];

  echo ($username." ".$password);

  $sql = $conn->prepare("SELECT * FROM user WHERE usc_email = ?;");
  $sql->bind_param('s', $username);
  $sql->execute();
  $ans = $sql->get_result();
  $row = $ans->fetch_assoc();

  $sql = $conn->prepare("SELECT * FROM user WHERE usc_id = ?;");
  $sql->bind_param('s', $username);
  $sql->execute();
  $ans2 = $sql->get_result();
  $row2 = $ans2->fetch_assoc();

  if(!empty($row)){
    $passHash = $row['password'];
    // verify if passHash, the hash generated by password_hash(), matches the password
    if(password_verify($password, $passHash)) {
      $uscid = $row['usc_id'];
      $email = $row['usc_email'];
      $name = $row['user_name'];
      $_SESSION['username'] = $name;
      $_SESSION['email'] = $email;
      $_SESSION['id'] = $uscid;
      header("Location: home-search.php");
    }
    else {
      header("Location: login.php?fail=true");
    }
  }else if(!empty($row2)){
    $passHash = $row2['password'];
    // verify if passHash, the hash generated by password_hash, matches the password
    if(password_verify($password, $passHash)) {
      $uscid = $row2['usc_id'];
      $email = $row2['usc_email'];
      $name = $row2['user_name'];
      $_SESSION['username'] = $name;
      $_SESSION['email'] = $email;
      $_SESSION['id'] = $uscid;
      header("Location: home-search.php");
    }
    else {
      header("Location: login.php?fail=true");
    }
  }else{
    header("Location: login.php?fail=true");
  }
?>